language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

before_install:
  - pip install cpp-coveralls

script:
  - COVERAGE=1 python setup.py build -f
  - python setup.py test
  - cp build/temp.*/* .
  - rm -rf build

  - python setup.py build -f
  - python setup.py test
  - python setup.py sdist
  - python setup.py bdist_wheel

after_success:
  - coveralls --exclude clinic --gcov-options '\-lp'